name: Deploy to release
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          pwd
          whoami
          cd sep-project/
          git checkout public/css/app.css public/js/app.js
          git pull
          ./vendor/bin/sail up -d 